DancingGoatCore/Models/References/ReferenceRepository.cs
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;

using Kentico.Content.Web.Mvc;

namespace DancingGoat.Models
{
    /// <summary>
    /// Encapsulates access to references.
    /// </summary>
    public class ReferenceRepository
    {
        private readonly IPageRetriever pageRetriever;


        /// <summary>
        /// Initializes a new instance of the <see cref="ReferenceRepository"/> class.
        /// </summary>
        /// <param name="pageRetriever">Retriever for pages based on given parameters.</param>
        public ReferenceRepository(IPageRetriever pageRetriever)
        {
            this.pageRetriever = pageRetriever;
        }


        /// <summary>
        /// Asynchronously returns an enumerable collection of references ordered by the node order.
        /// </summary>
        /// <param name="nodeAliasPath">The node alias path of the parent page in the content tree.</param>
        /// <param name="cancellationToken">The cancellation instruction.</param>
        /// <param name="count">The number of references to return. Use 0 as value to return all records.</param>
        public Task<IEnumerable<Reference>> GetReferencesAsync(string nodeAliasPath, CancellationToken cancellationToken, int count = 0)
        {
            return pageRetriever.RetrieveAsync<Reference>(
                query => query
                    .Path(nodeAliasPath, PathTypeEnum.Children)
                    .TopN(count)
                    .OrderBy("NodeOrder"),
                cache => cache
                    .Key($"{nameof(ReferenceRepository)}|{nameof(GetReferencesAsync)}|{nodeAliasPath}|{count}")
                    // Include path dependency to flush cache when a new child page is created or page order is changed.
                    .Dependencies((_, builder) => builder.PagePath(nodeAliasPath, PathTypeEnum.Children).PageOrder()),
                cancellationToken);
        }
    }
}

DancingGoatCore/Models/References/ReferenceViewModel.cs
using CMS.DocumentEngine.Types.DancingGoatCore;

using Kentico.Content.Web.Mvc;

namespace DancingGoat.Models
{
    public class ReferenceViewModel
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public string Text { get; set; }

        public string ImagePath { get; set; }


        public static ReferenceViewModel GetViewModel(Reference reference, IPageAttachmentUrlRetriever attachmentUrlRetriever)
        {
            if (reference == null)
            {
                return null;
            }

            return new ReferenceViewModel
            {
                Name = reference.ReferenceName,
                Description = reference.ReferenceDescription,
                Text = reference.ReferenceText,
                ImagePath = attachmentUrlRetriever.Retrieve(reference.Fields.Image).RelativePath
            };
        }
    }
}

DancingGoatCore/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using CMS.Base;
using CMS.Ecommerce;
using CMS.Globalization;
using CMS.Helpers;

using DancingGoat.Models;
using DancingGoat.Services;

using Kentico.Content.Web.Mvc;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace DancingGoat.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IShoppingService shoppingService;
        private readonly ICheckoutService checkoutService;
        private readonly ContactRepository contactRepository;
        private readonly ProductRepository productRepository;
        private readonly IPageUrlRetriever pageUrlRetriever;
        private readonly ISKUInfoProvider skuInfoProvider;
        private readonly ICountryInfoProvider countryInfoProvider;
        private readonly IStateInfoProvider stateInfoProvider;


        public CheckoutController(IShoppingService shoppingService, ContactRepository contactRepository, ProductRepository productRepository, 
            ICheckoutService checkoutService, IPageUrlRetriever pageUrlRetriever, ISKUInfoProvider skuInfoProvider, ICountryInfoProvider countryInfoProvider,
            IStateInfoProvider stateInfoProvider)
        {
            this.shoppingService = shoppingService;
            this.contactRepository = contactRepository;
            this.checkoutService = checkoutService;
            this.productRepository = productRepository;
            this.pageUrlRetriever = pageUrlRetriever;
            this.skuInfoProvider = skuInfoProvider;
            this.countryInfoProvider = countryInfoProvider;
            this.stateInfoProvider = stateInfoProvider;
        }


        public ActionResult ShoppingCart()
        {
            var viewModel = checkoutService.PrepareCartViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingCart(CartItemUpdateModel item, string update, string remove)
        {
            if (update != null)
            {
                return UpdateItem(item);
            }

            if (remove != null)
            {
                return RemoveItem(item);
            }

            var viewModel = checkoutService.PrepareCartViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingCartCheckout()
        {
            var cart = shoppingService.GetCurrentShoppingCart();
            var validationErrors = ShoppingCartInfoProvider.ValidateShoppingCart(cart);

            cart.Evaluate();

            if (!validationErrors.Any())
            {
                var customer = GetCustomerOrCreateFromAuthenticatedUser();
                if (customer != null)
                {
                    shoppingService.SetCustomer(customer);
                }

                shoppingService.SaveCart();
                return RedirectToAction("DeliveryDetails");
            }

            // Fill model state with errors from the check result
            ProcessCheckResult(validationErrors);

            var viewModel = checkoutService.PrepareCartViewModel();

            return View("ShoppingCart", viewModel);
        }


        public ActionResult DeliveryDetails()
        {
            var cart = shoppingService.GetCurrentShoppingCart();
            if (cart.IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = checkoutService.PrepareDeliveryDetailsViewModel();

            return View(viewModel);
        }


        public ActionResult PreviewAndPay()
        {
            if (shoppingService.GetCurrentShoppingCart().IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = checkoutService.PreparePreviewViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PreviewAndPay(PreviewViewModel model, [FromServices] IStringLocalizer<SharedResources> localizer)
        {
            var cart = shoppingService.GetCurrentShoppingCart();

            if (cart.IsEmpty)
            {
                ModelState.AddModelError("cart.empty", localizer["Please add some item to your shopping cart."]);

                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            if (!checkoutService.IsPaymentMethodValid(model.PaymentMethod.PaymentMethodID))
            {
                ModelState.AddModelError("PaymentMethod.PaymentMethodID", localizer["Select payment method"]);
            }
            else
            {
                shoppingService.SetPaymentOption(model.PaymentMethod.PaymentMethodID);
            }

            var validator = new CreateOrderValidator(cart, skuInfoProvider, countryInfoProvider, stateInfoProvider);

            if (!validator.Validate())
            {
                ProcessCheckResult(validator.Errors);
            }

            if (!ModelState.IsValid)
            {
                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            try
            {
                shoppingService.CreateOrder();
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError("cart.createordererror", ex.Message);
                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            return RedirectToAction("ThankYou");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeliveryDetails(DeliveryDetailsViewModel model, [FromServices] IStringLocalizer<SharedResources> localizer)
        {
            // Check the selected shipping option
            bool isShippingNeeded = shoppingService.GetCurrentShoppingCart().IsShippingNeeded;
            if (isShippingNeeded && !checkoutService.IsShippingOptionValid(model.ShippingOption.ShippingOptionID))
            {
                ModelState.AddModelError("ShippingOption.ShippingOptionID", localizer["Please select a delivery method"]);
            }

            // Check if the billing address's country and state are valid
            var countryStateViewModel = model.BillingAddress.BillingAddressCountryStateSelector;
            if (!checkoutService.IsCountryValid(countryStateViewModel.CountryID))
            {
                countryStateViewModel.CountryID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.CountryID", localizer["The Country field is required"]);
            }
            else if (!checkoutService.IsStateValid(countryStateViewModel.CountryID, countryStateViewModel.StateID))
            {
                countryStateViewModel.StateID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.StateID", localizer["The State field is required"]);
            }

            if (!ModelState.IsValid)
            {
                var viewModel = checkoutService.PrepareDeliveryDetailsViewModel(model.Customer, model.BillingAddress, model.ShippingOption);

                return View(viewModel);
            }

            var customer = GetCustomerOrCreateFromAuthenticatedUser() ?? new CustomerInfo();
            bool emailCanBeChanged = !User.Identity.IsAuthenticated || string.IsNullOrWhiteSpace(customer.CustomerEmail);
            model.Customer.ApplyToCustomer(customer, emailCanBeChanged);
            shoppingService.SetCustomer(customer);

            var modelAddressID = model.BillingAddress.BillingAddressSelector?.AddressID ?? 0;
            var billingAddress = checkoutService.GetAddress(modelAddressID) ?? new AddressInfo();

            model.BillingAddress.ApplyTo(billingAddress);
            billingAddress.AddressPersonalName = $"{customer.CustomerFirstName} {customer.CustomerLastName}";

            shoppingService.SetBillingAddress(billingAddress);
            shoppingService.SetShippingOption(model.ShippingOption?.ShippingOptionID ?? 0);

            return RedirectToAction("PreviewAndPay");
        }


        public ActionResult ThankYou()
        {
            var companyContact = contactRepository.GetCompanyContact();

            var viewModel = new ThankYouViewModel
            {
                Phone = companyContact.Phone
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddItem(CartItemUpdateModel item)
        {
            if (ModelState.IsValid)
            {
                shoppingService.AddItemToCart(item.SKUID, item.Units);
            }

            return RedirectToAction("ShoppingCart");
        }


        [HttpPost]
        public JsonResult CustomerAddress(int addressID)
        {
            var address = checkoutService.GetCustomerAddress(addressID); 

            if (address == null)
            {
                return null;
            }

            var responseModel = new
            {
                Line1 = address.AddressLine1,
                Line2 = address.AddressLine2,
                City = address.AddressCity,
                PostalCode = address.AddressZip,
                CountryID = address.AddressCountryID,
                StateID = address.AddressStateID,
                PersonalName = address.AddressPersonalName
            };

            return Json(responseModel);
        }


        public ActionResult ItemDetail(int skuId)
        {
            var product = productRepository.GetProductForSKU(skuId);

            if (product == null)
            {

DancingGoatCore/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using CMS.Base;
using CMS.Membership;
using CMS.Search;
using CMS.WebAnalytics;

using DancingGoat.Infrastructure;
using DancingGoat.Models;

using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace DancingGoat.Controllers
{
    public class SearchController : Controller
    {
        private const string INDEX_NAME = "DancingGoatCore.Index";
        private const int PAGE_SIZE = 5;
        private const int DEFAULT_PAGE_NUMBER = 1;

        private readonly TypedSearchItemViewModelFactory searchItemViewModelFactory;
        private readonly IPagesActivityLogger pagesActivityLogger;
        private readonly IAnalyticsLogger analyticsLogger;
        private readonly ISiteService siteService;


        public SearchController(TypedSearchItemViewModelFactory searchItemViewModelFactory, IPagesActivityLogger pagesActivityLogger,
            IAnalyticsLogger analyticsLogger, ISiteService siteService)
        {
            this.searchItemViewModelFactory = searchItemViewModelFactory;
            this.pagesActivityLogger = pagesActivityLogger;
            this.analyticsLogger = analyticsLogger;
            this.siteService = siteService;
        }


        // GET: Search
        public ActionResult Index(string searchText, int page = DEFAULT_PAGE_NUMBER)
        {
            if (String.IsNullOrWhiteSpace(searchText))
            {
                var empty = new SearchResultsModel
                {
                    Items = new List<SearchResultItemModel>()
                };
                return View(empty);
            }

            // Validate page number (starting from 1)
            page = Math.Max(page, DEFAULT_PAGE_NUMBER);

            var searchParameters = SearchParameters.PrepareForPages(searchText, new[] { INDEX_NAME }, page, PAGE_SIZE, MembershipContext.AuthenticatedUser);
            var searchResults = SearchHelper.Search(searchParameters);

            pagesActivityLogger.LogInternalSearch(searchText);

            var siteId = siteService.CurrentSite.SiteID;
            var culture = HttpContext.Features.Get<IRequestCultureFeature>().RequestCulture.Culture.Name;
            var hostAddress = HttpContext.Features.Get<IHttpConnectionFeature>().RemoteIpAddress.ToString();
            var uri = new Uri(HttpContext.Request.GetEncodedUrl());

            analyticsLogger.LogInternalSearchKeywords(new AnalyticsData(siteId, searchText, culture: culture, uri: uri, hostAddress: hostAddress));

            var searchResultItemModels = searchResults.Items
                .Select(searchItemViewModelFactory.GetTypedSearchResultItemModel);

            var model = new SearchResultsModel
            {
                Items = searchResultItemModels.ToList(),
                Query = searchText,
                CurrentPage = page,
                NumberOfPages = (int)Math.Ceiling(searchResults.TotalNumberOfResults / (double)PAGE_SIZE)
            };

            return View(model);
        }
    }
}

DancingGoatCore/Views/Shared/_GoogleMaps.cshtml
@using Microsoft.Extensions.Configuration

@inject IConfiguration Configuration

<script src="https://maps.googleapis.com/maps/api/js?key=@Configuration["GoogleMapsApiKey"]"></script>
<script src="~/Scripts/map.js"></script>

DancingGoatCore/Views/Shared/_LandingPageLayout.cshtml
@using Kentico.Activities.Web.Mvc
@using Kentico.OnlineMarketing.Web.Mvc

@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head id="head">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="UTF-8" />
    @Html.Kentico().PageDescription()
    @Html.Kentico().PageKeywords()
    @Html.Kentico().PageTitle()
    <link rel="icon" href="~/content/images/favicon.svg" type="image/svg+xml" />
    <link href="~/Content/Styles/Landing-page.css" rel="stylesheet" type="text/css" />
    <link rel="canonical" href="@Url.Kentico().PageCanonicalUrl()" />
    <page-builder-styles />
    @Html.Kentico().ABTestLoggerScript()
    @Html.Kentico().ActivityLoggingScript()
</head>
<body>
    <div class="page-wrap">
        <vc:tracking-consent />
        @RenderBody()
    </div>
    <div class="footer-wrapper">
        <footer>
            <div class="footer-container">
                <div class="container">
                    Copyright &copy; @DateTime.Now.Year Dancing Goat. All rights reserved.
                </div>
            </div>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <page-builder-scripts />
</body>
</html>

DancingGoatCore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@using Kentico.Activities.Web.Mvc
@using Kentico.Membership.Web.Mvc
@using Kentico.OnlineMarketing.Web.Mvc

@using DancingGoat.Helpers
@using DancingGoat.Widgets

@inject IHtmlLocalizer<SharedResources> HtmlLocalizer

@{
    const string ENGLISH = "English";
    const string ESPANOL = "Español";

    var currentCultureCode = Convert.ToString(@ViewContext.RouteData.Values["culture"]);
    var currentLanguage = currentCultureCode.Equals("es-es", StringComparison.OrdinalIgnoreCase) ? "ES" : "EN";
}

<!DOCTYPE html>

<html>
<head id="head">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="UTF-8" />
    @Html.Kentico().PageDescription()
    @Html.Kentico().PageKeywords()
    @Html.Kentico().PageTitle(ViewBag.Title as string)
    <link rel="icon" href="~/content/images/favicon.svg" type="image/svg+xml" />
    <link href="~/Content/Styles/Site.css" rel="stylesheet" type="text/css" />
    <link rel="canonical" href="@Url.Kentico().PageCanonicalUrl()" />
    @RenderSection("styles", required: false)
    @Html.Kentico().ABTestLoggerScript()
    @Html.Kentico().ActivityLoggingScript()
    @Html.Kentico().WebAnalyticsLoggingScript()
    <page-builder-styles />
</head>
<body class="@ViewData["PageClass"]">
    <div class="page-wrap">
        <vc:tracking-consent />
        <header data-ktc-search-exclude>
            <nav class="navigation">
                <div class="nav-logo">
                    <div class="logo-wrapper">
                        <a href="@Url.Kentico().PageUrl(ContentItemIdentifiers.HOME)" class="logo-link">
                            <img class="logo-image" alt="Dancing Goat" src="~/Content/Images/logo.svg" />
                        </a>
                    </div>
                </div>
                <vc:navigation footer-navigation="false" />
                <ul class="additional-menu">
                    <li class="search-menu-item">
                        <form asp-action="Index" asp-controller="Search" method="get" class="searchBox">
                            <input name="searchtext" type="text" placeholder="@HtmlLocalizer["Search"]" autocomplete="off" />
                            <input type="submit" value="" class="search-box-btn" />
                        </form>
                    </li>
                    <li class="dropdown">
                        <a title="User" class="dropbtn">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <img src="@Url.Kentico().AvatarUrl(User.Identity.Name, pathToDefaultAvatar: "~/Content/Images/default-avatar.png")" class="dropdown-desktop-avatar" alt="avatar" />
                            }
                            else
                            {
                                <svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M5.44934 14H15.4493C18.2108 14 20.4493 16.2386 20.4493 19C20.4493 19.5523 20.0016 20 19.4493 20C18.9365 20 18.5138 19.614 18.4561 19.1166L18.4442 18.8237C18.3564 17.3072 17.1421 16.093 15.6256 16.0051L15.4493 16H5.44934C3.79249 16 2.44934 17.3431 2.44934 19C2.44934 19.5523 2.00163 20 1.44934 20C0.897056 20 0.449341 19.5523 0.449341 19C0.449341 16.3112 2.57165 14.1182 5.23245 14.0046L5.44934 14H15.4493H5.44934ZM10.4493 0C13.763 0 16.4493 2.68629 16.4493 6C16.4493 9.31371 13.763 12 10.4493 12C7.13563 12 4.44934 9.31371 4.44934 6C4.44934 2.68629 7.13563 0 10.4493 0ZM10.4493 2C8.2402 2 6.44934 3.79086 6.44934 6C6.44934 8.20914 8.2402 10 10.4493 10C12.6585 10 14.4493 8.20914 14.4493 6C14.4493 3.79086 12.6585 2 10.4493 2Z" fill="currentColor" />
                                </svg>
                            }
                        </a>
                        <div class="dropdown-content">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a asp-controller="Account" asp-action="YourAccount">@HtmlLocalizer["Your&nbsp;account"]</a>
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input type="submit" value="@HtmlLocalizer["Sign out"]" class="sign-out-button" />
                                </form>
                            }
                            else
                            {
                                <a asp-controller="Account" asp-action="Register">@HtmlLocalizer["Register"]</a>
                                <a asp-controller="Account" asp-action="Login">@HtmlLocalizer["Login"]</a>
                            }
                        </div>
                    </li>
                    @if (Context.Response.StatusCode == (int)System.Net.HttpStatusCode.OK)
                    {
                        <li class="dropdown">
                            <a class="dropbtn">@currentLanguage</a>
                            <div class="dropdown-content">
                                <culture-link link-text="@ENGLISH" culture-name="en-US" />
                                <culture-link link-text="@ESPANOL" culture-name="es-ES" />
                            </div>
                        </li>
                    }
                    <li>
                        <a asp-controller="Checkout" asp-action="ShoppingCart" class="navigation__cta">
                            <svg width="26" height="24" viewBox="0 0 26 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M9.94934 19C10.7778 19 11.4493 19.6716 11.4493 20.5C11.4493 21.3284 10.7778 22 9.94934 22C9.12091 22 8.44934 21.3284 8.44934 20.5C8.44934 19.6716 9.12091 19 9.94934 19ZM18.9493 19C19.7778 19 20.4493 19.6716 20.4493 20.5C20.4493 21.3284 19.7778 22 18.9493 22C18.1209 22 17.4493 21.3284 17.4493 20.5C17.4493 19.6716 18.1209 19 18.9493 19ZM4.44934 2H6.44934C6.90494 2 7.29765 2.30684 7.4144 2.73774L7.43771 2.84794L7.92264 6H22.4493C23.0491 6 23.5043 6.52068 23.4445 7.10035L23.4255 7.21693L21.7736 14.6508C21.4818 15.9637 20.3552 16.9143 19.0273 16.9945L18.845 17H10.1652C8.74369 17 7.52631 16.0044 7.23199 14.6299L7.20006 14.4562L5.59142 4H4.44934C3.89706 4 3.44934 3.55228 3.44934 3C3.44934 2.48716 3.83538 2.06449 4.33272 2.00673L4.44934 2H6.44934H4.44934ZM21.2027 8H8.23034L9.17681 14.1521C9.24608 14.6024 9.60907 14.9438 10.0527 14.9937L10.1652 15H18.845C19.2746 15 19.6514 14.7265 19.7896 14.3285L19.8212 14.2169L21.2027 8Z" fill="currentColor" />
                            </svg>
                        </a>
                    </li>
                    <li class="nav-toggle">
                        <div class="nav-toggle-inner">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </div>
                    </li>
                </ul>
            </nav>
            <div class="search-mobile">
                <form asp-action="Index" asp-controller="Search" method="get" class="searchBox">
                    <input name="searchtext" type="text" placeholder="@HtmlLocalizer["Search"]" autocomplete="off" />
                    <input type="submit" value="" class="search-box-btn" />
                </form>
            </div>
        </header>
        <div class="container">
            <div class="page-container-inner">
                @RenderBody()

                <div class="clear"></div>
            </div>
        </div>
    </div>
    <div class="footer-wrapper">
        <footer data-ktc-search-exclude>
            <div class="footer-container">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-md-8 col-lg-7 footer-col">
                            <h5 class="contact-title">@HtmlLocalizer["Contact"]</h5>
                            <vc:company-address />
                            <vc:social-links />
                        </div>
                        <div class="col-xs-12 col-md-4 col-lg-5 footer-col">
                            <h5>@HtmlLocalizer["News & Updates"]</h5>
                            @await Html.Kentico().RenderStandaloneWidgetAsync(NewsletterSubscriptionViewComponent.IDENTIFIER, new NewsletterSubscriptionProperties())

                            <div class="copyright">Copyright &copy; @DateTime.Now.Year Dancing Goat. All rights reserved.</div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/responsiveMenuDropdown.js"></script>
    <script src="~/Scripts/mobileMenu.js"></script>
    <page-builder-scripts />

    @RenderSection("scripts", required: false)

</body>
</html>

DancingGoatCore/Views/Shared/_ManufacturerList.cshtml
@using DancingGoat.Models;
@model IEnumerable<ManufactureListItemViewModel>

<div class="row manufacturer-list">
    @if (Model != null && Model.Any())
    {
        foreach (var manufacturer in Model)
        {
            <div class="col-xs-12 col-md-4 col-lg-3 manufacturer-item">
                <a href="@manufacturer.Url">
                    <img src="@manufacturer.ImagePath" alt="@manufacturer.Name" title="@manufacturer.Name" />
                </a>
            </div>
        }
    }
    else
    {
        <span class="ContentLabel">@HtmlLocalizer["No matching manufacturers."]</span>
    }
</div>

DancingGoatCore/Views/Shared/_Reference.cshtml
@model DancingGoat.Models.ReferenceViewModel

<section class="row reference">
    <div class="title-wrapper">
        <h1 class="title-tab">@HtmlLocalizer["Reference"]</h1>
    </div>
    <div class="col-sm-12 full-height">
        <div class="col-md-5 col-lg-3 sm-hidden">
            <img src="@Model.ImagePath" alt="@Model.Name" title="@Model.Name" class="image-responsive" />
        </div>
        <div class="col-sm-12 col-md-7 col-lg-9 quote">
            <div class="text"><span>&ldquo;</span>@Html.Raw(Model.Text)<span>&rdquo;</span></div>
            <div class="name-and-description">
                <div class="name">@Html.Raw(Model.Name)</div>
                <div class="description">@Html.Raw(Model.Description)</div>
            </div>
        </div>
    </div>
</section>

DancingGoatCore/Views/Shared/_StoreLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="product-page-container">
    <nav class="sub-menu row" data-ktc-search-exclude>
        <div class="store-menu-list row">
            <ul>
                <li>
                    <a href="@Url.Kentico().PageUrl(ContentItemIdentifiers.COFFEES)">@HtmlLocalizer["Coffees"]</a>
                </li>
                <li>
                    <a href="@Url.Kentico().PageUrl(ContentItemIdentifiers.BREWERS)">@HtmlLocalizer["Brewers"]</a>
                </li>
                <li>
                    <a href="@Url.Kentico().PageUrl(ContentItemIdentifiers.ACCESSORIES)">@HtmlLocalizer["Accessories"]</a>
                </li>
                <li>
                    <a href="@Url.Kentico().PageUrl(ContentItemIdentifiers.GRINDERS)">@HtmlLocalizer["Grinders"]</a>
                </li>
            </ul>
        </div>
    </nav>
    @RenderBody()
</div>

@section Scripts {
    @RenderSection("scripts", required: false)
}

DancingGoatCore/Views/Shared/_StoreProductList.cshtml
@using DancingGoat.Models
@model IEnumerable<ProductListItemViewModel>
    
@if (Model.Any())
{
    foreach (var product in Model)
    {
        <!-- 4 products on row for large screen -->
        <div class="col-md-4 col-lg-3">
            @Html.DisplayFor(m => product, "ProductListItem")
        </div>
    }
}
else
{
    <span class="ContentLabel">@HtmlLocalizer["No matching products."]</span>
}