DancingGoatCore/Models/Orders/OrderAddressViewModel.cs
using System;

using CMS.Ecommerce;
using CMS.Globalization;

namespace DancingGoat.Models
{
    public class OrderAddressViewModel
    {
        public string AddressLine1 { get; set; }


        public string AddressLine2 { get; set; }


        public string AddressCity { get; set; }


        public string AddressPostalCode { get; set; }


        public string AddressState { get; set; }


        public string AddressCountry { get; set; }


        public OrderAddressViewModel()
        {
        }


        public OrderAddressViewModel(OrderAddressInfo address, ICountryInfoProvider countryInfoProvider, IStateInfoProvider stateInfoProvider)
        {
            if (address == null)
            {
                return;
            }

            if (countryInfoProvider == null)
            {
                throw new ArgumentNullException(nameof(countryInfoProvider));
            }
            if (stateInfoProvider == null)
            {
                throw new ArgumentNullException(nameof(stateInfoProvider));
            }

            AddressLine1 = address.AddressLine1;
            AddressLine2 = address.AddressLine2;
            AddressCity = address.AddressCity;
            AddressPostalCode = address.AddressZip;
            AddressState = stateInfoProvider.Get(address.AddressStateID)?.StateDisplayName ?? String.Empty;
            AddressCountry = countryInfoProvider.Get(address.AddressCountryID)?.CountryDisplayName ?? String.Empty;
        }
    }
}

DancingGoatCore/Models/Orders/OrderDetailViewModel.cs
using System;
using System.Collections.Generic;

namespace DancingGoat.Models
{
    public class OrderDetailViewModel
    {
        private readonly string currencyFormatString;


        public string InvoiceNumber { get; set; }

        public decimal TotalPrice { get; set; }

        public string StatusName { get; set; }

        public OrderAddressViewModel OrderAddress { get; set; }

        public IEnumerable<OrderItemViewModel> OrderItems { get; set; }


        public OrderDetailViewModel(string currencyFormatString)
        {
            if (string.IsNullOrEmpty(currencyFormatString))
            {
                throw new ArgumentException($"{nameof(currencyFormatString)} is not defined.");
            }

            this.currencyFormatString = currencyFormatString;
        }

        public string FormatPrice(decimal price)
        {
            return string.Format(currencyFormatString, price);
        }
    }
}

DancingGoatCore/Models/Orders/OrderItemViewModel.cs
using Kentico.Content.Web.Mvc;

namespace DancingGoat.Models
{
    public class OrderItemViewModel
    {
        public int SKUID { get; set; }

        public string SKUImagePath { get; set; }

        public string SKUName { get; set; }

        public int UnitCount { get; set; }

        public decimal UnitPrice { get; set; }

        public decimal TotalPriceInMainCurrency { get; set; }
    }
}

DancingGoatCore/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using CMS.Base;
using CMS.Ecommerce;
using CMS.Globalization;
using CMS.Helpers;

using DancingGoat.Models;
using DancingGoat.Services;

using Kentico.Content.Web.Mvc;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace DancingGoat.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IShoppingService shoppingService;
        private readonly ICheckoutService checkoutService;
        private readonly ContactRepository contactRepository;
        private readonly ProductRepository productRepository;
        private readonly IPageUrlRetriever pageUrlRetriever;
        private readonly ISKUInfoProvider skuInfoProvider;
        private readonly ICountryInfoProvider countryInfoProvider;
        private readonly IStateInfoProvider stateInfoProvider;


        public CheckoutController(IShoppingService shoppingService, ContactRepository contactRepository, ProductRepository productRepository, 
            ICheckoutService checkoutService, IPageUrlRetriever pageUrlRetriever, ISKUInfoProvider skuInfoProvider, ICountryInfoProvider countryInfoProvider,
            IStateInfoProvider stateInfoProvider)
        {
            this.shoppingService = shoppingService;
            this.contactRepository = contactRepository;
            this.checkoutService = checkoutService;
            this.productRepository = productRepository;
            this.pageUrlRetriever = pageUrlRetriever;
            this.skuInfoProvider = skuInfoProvider;
            this.countryInfoProvider = countryInfoProvider;
            this.stateInfoProvider = stateInfoProvider;
        }


        public ActionResult ShoppingCart()
        {
            var viewModel = checkoutService.PrepareCartViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingCart(CartItemUpdateModel item, string update, string remove)
        {
            if (update != null)
            {
                return UpdateItem(item);
            }

            if (remove != null)
            {
                return RemoveItem(item);
            }

            var viewModel = checkoutService.PrepareCartViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingCartCheckout()
        {
            var cart = shoppingService.GetCurrentShoppingCart();
            var validationErrors = ShoppingCartInfoProvider.ValidateShoppingCart(cart);

            cart.Evaluate();

            if (!validationErrors.Any())
            {
                var customer = GetCustomerOrCreateFromAuthenticatedUser();
                if (customer != null)
                {
                    shoppingService.SetCustomer(customer);
                }

                shoppingService.SaveCart();
                return RedirectToAction("DeliveryDetails");
            }

            // Fill model state with errors from the check result
            ProcessCheckResult(validationErrors);

            var viewModel = checkoutService.PrepareCartViewModel();

            return View("ShoppingCart", viewModel);
        }


        public ActionResult DeliveryDetails()
        {
            var cart = shoppingService.GetCurrentShoppingCart();
            if (cart.IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = checkoutService.PrepareDeliveryDetailsViewModel();

            return View(viewModel);
        }


        public ActionResult PreviewAndPay()
        {
            if (shoppingService.GetCurrentShoppingCart().IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = checkoutService.PreparePreviewViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PreviewAndPay(PreviewViewModel model, [FromServices] IStringLocalizer<SharedResources> localizer)
        {
            var cart = shoppingService.GetCurrentShoppingCart();

            if (cart.IsEmpty)
            {
                ModelState.AddModelError("cart.empty", localizer["Please add some item to your shopping cart."]);

                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            if (!checkoutService.IsPaymentMethodValid(model.PaymentMethod.PaymentMethodID))
            {
                ModelState.AddModelError("PaymentMethod.PaymentMethodID", localizer["Select payment method"]);
            }
            else
            {
                shoppingService.SetPaymentOption(model.PaymentMethod.PaymentMethodID);
            }

            var validator = new CreateOrderValidator(cart, skuInfoProvider, countryInfoProvider, stateInfoProvider);

            if (!validator.Validate())
            {
                ProcessCheckResult(validator.Errors);
            }

            if (!ModelState.IsValid)
            {
                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            try
            {
                shoppingService.CreateOrder();
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError("cart.createordererror", ex.Message);
                var viewModel = checkoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            return RedirectToAction("ThankYou");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeliveryDetails(DeliveryDetailsViewModel model, [FromServices] IStringLocalizer<SharedResources> localizer)
        {
            // Check the selected shipping option
            bool isShippingNeeded = shoppingService.GetCurrentShoppingCart().IsShippingNeeded;
            if (isShippingNeeded && !checkoutService.IsShippingOptionValid(model.ShippingOption.ShippingOptionID))
            {
                ModelState.AddModelError("ShippingOption.ShippingOptionID", localizer["Please select a delivery method"]);
            }

            // Check if the billing address's country and state are valid
            var countryStateViewModel = model.BillingAddress.BillingAddressCountryStateSelector;
            if (!checkoutService.IsCountryValid(countryStateViewModel.CountryID))
            {
                countryStateViewModel.CountryID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.CountryID", localizer["The Country field is required"]);
            }
            else if (!checkoutService.IsStateValid(countryStateViewModel.CountryID, countryStateViewModel.StateID))
            {
                countryStateViewModel.StateID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.StateID", localizer["The State field is required"]);
            }

            if (!ModelState.IsValid)
            {
                var viewModel = checkoutService.PrepareDeliveryDetailsViewModel(model.Customer, model.BillingAddress, model.ShippingOption);

                return View(viewModel);
            }

            var customer = GetCustomerOrCreateFromAuthenticatedUser() ?? new CustomerInfo();
            bool emailCanBeChanged = !User.Identity.IsAuthenticated || string.IsNullOrWhiteSpace(customer.CustomerEmail);
            model.Customer.ApplyToCustomer(customer, emailCanBeChanged);
            shoppingService.SetCustomer(customer);

            var modelAddressID = model.BillingAddress.BillingAddressSelector?.AddressID ?? 0;
            var billingAddress = checkoutService.GetAddress(modelAddressID) ?? new AddressInfo();

            model.BillingAddress.ApplyTo(billingAddress);
            billingAddress.AddressPersonalName = $"{customer.CustomerFirstName} {customer.CustomerLastName}";

            shoppingService.SetBillingAddress(billingAddress);
            shoppingService.SetShippingOption(model.ShippingOption?.ShippingOptionID ?? 0);

            return RedirectToAction("PreviewAndPay");
        }


        public ActionResult ThankYou()
        {
            var companyContact = contactRepository.GetCompanyContact();

            var viewModel = new ThankYouViewModel
            {
                Phone = companyContact.Phone
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddItem(CartItemUpdateModel item)
        {
            if (ModelState.IsValid)
            {
                shoppingService.AddItemToCart(item.SKUID, item.Units);
            }

            return RedirectToAction("ShoppingCart");
        }


        [HttpPost]
        public JsonResult CustomerAddress(int addressID)
        {
            var address = checkoutService.GetCustomerAddress(addressID); 

            if (address == null)
            {
                return null;
            }

            var responseModel = new
            {
                Line1 = address.AddressLine1,
                Line2 = address.AddressLine2,
                City = address.AddressCity,
                PostalCode = address.AddressZip,
                CountryID = address.AddressCountryID,
                StateID = address.AddressStateID,
                PersonalName = address.AddressPersonalName
            };

            return Json(responseModel);
        }


        public ActionResult ItemDetail(int skuId)
        {
            var product = productRepository.GetProductForSKU(skuId);

            if (product == null)
            {

DancingGoatCore/Controllers/OrdersController.cs
using System.Linq;
using System.Net;

using CMS.Ecommerce;
using CMS.Globalization;

using DancingGoat.Models;

using Kentico.Content.Web.Mvc;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DancingGoat.Controllers
{
    public class OrdersController : Controller
    {
        private readonly OrderRepository orderRepository;
        private readonly IShoppingService shoppingService;
        private readonly ICurrencyInfoProvider currencyInfoProvider;
        private readonly IOrderStatusInfoProvider orderStatusInfoProvider;
        private readonly ICountryInfoProvider countryInfoProvider;
        private readonly IStateInfoProvider stateInfoProvider;


        private CustomerInfo CurrentCustomer => shoppingService.GetCurrentCustomer();


        public OrdersController(OrderRepository orderRepository, IShoppingService shoppingService, ICurrencyInfoProvider currencyInfoProvider, IOrderStatusInfoProvider orderStatusInfoProvider,
            ICountryInfoProvider countryInfoProvider, IStateInfoProvider stateInfoProvider)
        {
            this.orderRepository = orderRepository;
            this.shoppingService = shoppingService;
            this.currencyInfoProvider = currencyInfoProvider;
            this.orderStatusInfoProvider = orderStatusInfoProvider;
            this.countryInfoProvider = countryInfoProvider;
            this.stateInfoProvider = stateInfoProvider;
        }


        // GET: Orders
        [Authorize]
        public ActionResult Index()
        {
            var currentCustomer = shoppingService.GetCurrentCustomer();
            var orders = currentCustomer != null
                ? orderRepository.GetByCustomerId(currentCustomer.CustomerID).Select(order => new OrdersListViewModel(order, currencyInfoProvider, orderStatusInfoProvider))
                : Enumerable.Empty<OrdersListViewModel>();

            return View(orders);
        }


        // GET: Orders/OrderDetail
        [Authorize]
        public ActionResult OrderDetail(int? orderID)
        {
            if (orderID == null)
            {
                return RedirectToAction("Index");
            }

            var order = orderRepository.GetById(orderID.Value);

            if ((order == null) || (order.OrderCustomerID != CurrentCustomer?.CustomerID))
            {
                return RedirectToAction("Error", "HttpErrors", new { code = (int)HttpStatusCode.NotFound });
            }

            var currency = currencyInfoProvider.Get(order.OrderCurrencyID);

            return View(new OrderDetailViewModel(currency.CurrencyFormatString)
            {
                InvoiceNumber = order.OrderInvoiceNumber,
                TotalPrice = order.OrderTotalPrice,
                StatusName = orderStatusInfoProvider.Get(order.OrderStatusID)?.StatusDisplayName,
                OrderAddress = new OrderAddressViewModel(order.OrderBillingAddress, countryInfoProvider, stateInfoProvider),
                OrderItems = OrderItemInfoProvider.GetOrderItems(order.OrderID).Select(orderItem =>
                {
                    return new OrderItemViewModel
                    {
                        SKUID = orderItem.OrderItemSKUID,
                        SKUName = orderItem.OrderItemSKUName,
                        SKUImagePath = string.IsNullOrEmpty(orderItem.OrderItemSKU.SKUImagePath) ? null : new FileUrl(orderItem.OrderItemSKU.SKUImagePath, true).WithSizeConstraint(SizeConstraint.MaxWidthOrHeight(70)).RelativePath,
                        TotalPriceInMainCurrency = orderItem.OrderItemTotalPriceInMainCurrency,
                        UnitCount = orderItem.OrderItemUnitCount,
                        UnitPrice = orderItem.OrderItemUnitPrice
                    };
                })
            });
        }
    }
}

DancingGoatCore/Views/Orders/Index.cshtml
@model IEnumerable<DancingGoat.Models.OrdersListViewModel>

@{
    ViewBag.Title = HtmlLocalizer["Your orders"].Value;
    ViewData["PageClass"] = "inverted no-bg";
}

<a asp-controller="Account" asp-action="YourAccount">&larr; @HtmlLocalizer["back to Your Account"]</a>

<h2>@HtmlLocalizer["Your orders"]</h2>

<div id="no-more-tables">
    <table class="orders-table">
        <thead>
            <tr>
                <th class="column-id">@HtmlLocalizer["Order ID"]</th>
                <th class="column-date">@HtmlLocalizer["Order date"]</th>
                <th class="column-status">@HtmlLocalizer["Status"]</th>
                <th class="column-total">@HtmlLocalizer["Total"]</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td class="column-id">
                        <span class="strong">@order.OrderInvoiceNumber</span>
                        <a asp-action="OrderDetail" asp-route-orderID="@order.OrderID" class="btn btn-terciary">@HtmlLocalizer["Order Detail"]</a>
                    </td>
                    <td class="column-date">@order.OrderDate</td>
                    <td class="column-status">
                        <span class="status">
                            @HtmlLocalizer[order.StatusName]
                        </span>
                    </td>
                    <td class="column-total">@order.FormattedTotalPrice</td>
                </tr>
            }
        </tbody>
    </table>
</div>

DancingGoatCore/Views/Orders/OrderDetail.cshtml
@model DancingGoat.Models.OrderDetailViewModel

@{
    ViewBag.Title = HtmlLocalizer["Order Detail"].Value;
    ViewData["PageClass"] = "inverted";
}

<a asp-controller="Orders" asp-action="Index">&larr; @HtmlLocalizer["back to Your Orders"]</a>
<h2>
    @HtmlLocalizer["Order Detail"]
    @Model.InvoiceNumber - @HtmlLocalizer[Model.StatusName]
</h2>
<hr />
<div>
    <div class="row">
        <div class="col-md-6">
            <h3>@HtmlLocalizer["Billing details"]</h3>
            @Html.DisplayFor(m => m.OrderAddress)
        </div>
        <div class="col-md-6">
            <h3>@HtmlLocalizer["Shipping details"]</h3>
            @Html.DisplayFor(m => m.OrderAddress)
        </div>
    </div>
    <div>
        <h4>@HtmlLocalizer["Order Items"]</h4>
        <hr />
        @foreach (var orderItem in Model.OrderItems)
        {
            <div class="row order-item">
                <div class="col-md-10">
                    @if (!string.IsNullOrEmpty(orderItem.SKUImagePath))
                    {
                        <div class="order-item-image">
                            <a asp-controller="Checkout" asp-action="ItemDetail" asp-route-skuId="@orderItem.SKUID">
                                <img src="@orderItem.SKUImagePath" alt="@orderItem.SKUName" title="@orderItem.SKUName" />
                            </a>
                        </div>
                    }
                    <div class="order-item-info">
                        @Html.ActionLink(orderItem.SKUName, "ItemDetail", "Checkout", new {skuId = orderItem.SKUID }, null)
                    </div>
                    <div class="order-item-amount">
                        <div>
                            <span class="strong">Qty: </span>
                            <span>@orderItem.UnitCount</span>
                        </div>
                        <div>
                            <span class="strong">Unit price: </span>
                            <span>@Model.FormatPrice(orderItem.UnitPrice)</span>
                        </div>

                    </div>

                    @Html.ValidationMessage(orderItem.UnitPrice.ToString(), new {@class = "red"})

                </div>
                <div class="col-md-2 order-item-subtotal">
                    <span>@Model.FormatPrice(orderItem.TotalPriceInMainCurrency)</span>
                </div>
            </div>
            <hr />
        }
        <div class="order-total-price">
            <div>
                <span class="strong">@HtmlLocalizer["TOTAL (incl. tax):"]</span>
                <span class="total-price">@Model.FormatPrice(Model.TotalPrice)</span>
            </div>
        </div>

    </div>
</div>